"""
Single Channel Analysis (SCW inner channel / Pb outer channel fuel pin),
rebuilt from SCA_Clear_2.py to source water properties from the finished
IAPWS_95.py module instead of the pip `iapws` package and the static
Props2.csv table. All of the underlying physics (Shen/Dittus/Swenson
correlations, gap conductance, fuel conduction, axial marching) is
unchanged -- only where the SCW property numbers come from is different:

  - Props2.csv (T -> mu,k,h,cp only, no rho -- which is why Swenson()
    fell back to calling pip `iapws.IAPWS95(T=,P=)` directly) is replaced
    by a table built on the fly from IAPWS_95.rho_Tp()+helmholtz(), at
    whatever operating pressure a given run uses. It also gets a 'rho'
    column, so Swenson() can go through the same Property() lookup as
    everything else instead of a separate direct call.
  - Property() itself now builds its interp1d objects once per table and
    caches them, instead of reconstructing one on every single lookup --
    with thousands of nested fsolve calls per run that reconstruction was
    the dominant cost (a full 400-step baseline run took ~6 minutes; see
    the __main__ block below for a like-for-like comparison).

Everything is wrapped in run_SCA(...) so this module can be called
repeatedly (varying pitch, radii, mass fluxes, pressure, inlet temps,
LHGR, ...) to generate a training set for the SCA PINN.
"""
import numpy as np
import scipy
from scipy.optimize import fsolve, brentq
from scipy.interpolate import interp1d

import Liquid_Metals as LM
from IAPWS_95 import IAPWS95
import torch
sigma = scipy.constants.sigma  # Stefan-Boltzmann constant


# =============================================================================
# SCW property table, built from IAPWS_95 at a fixed operating pressure.
# Standing in for Props2.csv, but generated by our own finished library and
# carrying a density column (T,mu,k,h,cp,rho all in the same units the rest
# of the script already expects: mu[Pa.s], k[W/m/K], h[J/kg], cp[J/kg/K]).
# =============================================================================

def Newton(func, guess, tol=1e-8, max_iters=1000):
    x = torch.tensor([float(guess)], dtype=torch.float64, requires_grad=True)

    for i in range(1, max_iters + 1):
        y = func(x)
        y_x = torch.autograd.grad(y, x, grad_outputs=torch.ones_like(y))[0]

        with torch.no_grad():
            x_new = x - y / y_x
            res = torch.abs(x_new - x)
            x = x_new.requires_grad_(True)

        if torch.all(res < tol):
            print(f'{i} iterations')
            return x.detach()

    print('Unconverged: max iters reached')
    return x.detach()


def build_scw_table(p, Tmin=290.0, Tmax=1000.0, n=3000):
    T = np.linspace(Tmin, Tmax, n)
    rho = IAPWS95.rho_Tp(T, p)
    d = IAPWS95.helmholtz(rho, T)
    return {
        'T':  T,
        'rho': rho,
        'mu': IAPWS95.mu(d),
        'k':  IAPWS95.lam(d),
        'h':  IAPWS95.h(d),   # J/kg  (default units)
        'cp': IAPWS95.cp(d),  # J/kg/K
    }


def make_Property(df):
    """Same Property(Prop, prop) interface as SCA_Clear_2.py, but the
    interp1d for a given (x-column, y-column) pair is built once and
    reused, instead of being rebuilt on every lookup."""
    cache = {}

    def Property(Prop, prop):
        key = (Prop[0], prop)
        f = cache.get(key)
        if f is None:
            f = interp1d(df[Prop[0]], df[prop], kind='linear', fill_value="extrapolate")
            cache[key] = f
        return f(Prop[1])

    return Property


# =============================================================================
# Heat-transfer correlations (unchanged physics from SCA_Clear_2.py)
# =============================================================================
def Shen(T, G, D):
    props = LM.Props(LM.Lead, T)
    Re, Pr = LM.RePr(G, D, props)
    Pe = Re*Pr
    k = props['k']
    Nu = 10.287*Pe**(-0.1175) + (0.0599/2.5)*Pe**(0.7575)
    htc = Nu*(k/D)
    return htc


def Dittus(Property, Tm, p, G, D):
    mu, cp, k = Property(['T', Tm], 'mu'), Property(['T', Tm], 'cp'), Property(['T', Tm], 'k')
    Pr = mu*cp/k
    Re = G*D/mu
    return (0.023*Re**(0.8)*Pr**(0.3))*k/D


def psi(pitch, D):
    q = pitch/D
    val = 0.9217 + 0.1478*(q) - 0.1130*np.exp(-7*(q-1))
    return val


def Swenson(Property, Tb, Ts, p, G, D):
    rho_s, rho_b = Property(['T', Ts], 'rho'), Property(['T', Tb], 'rho')
    h_s, cp_s, mu_s, k_s = (Property(['T', Ts], 'h'), Property(['T', Ts], 'cp'),
                             Property(['T', Ts], 'mu'), Property(['T', Ts], 'k'))
    h_b, cp_b = Property(['T', Tb], 'h'), Property(['T', Tb], 'cp')
    cp_bar = (h_s - h_b)/(Ts - Tb)
    Re_s, Pr_s = G*D/mu_s, mu_s*cp_s/k_s
    A, B = cp_bar/cp_b, rho_s/rho_b
    Nu_s = 0.00459*Re_s**(0.92)*Pr_s**(0.61)*A**(0.61)*B**(0.23)
    htc = Nu_s*k_s/D
    return htc


def htc_scw(Property, Tm, qp, p, G, D):
    guess = Tm + qp/(np.pi*D*Dittus(Property, Tm, p, G, D))

    def res(Tco):
        Tco = float(Tco[0])
        htc = Swenson(Property, Tm, Tco, p, G, D)
        residue = (Tco - Tm) - qp/(np.pi*D*htc)
        return residue
    Tco = fsolve(res,guess)#Newton(res,guess)
    htc_val = Swenson(Property, Tm, Tco, p, G, D)
    return htc_val


def gap(qp, delta, Tci, rci, rfo):
    def res(Tfo):
        Tave = (Tfo + Tci)/2
        kgas = 15.8E-4 * Tave**(-0.79)
        htc_cond = kgas/delta
        htc_rad = sigma * (Tfo**4 - Tci**4)/(Tfo - Tci)
        htc_net = htc_cond + htc_rad
        residue = Tfo - (Tci + qp/(np.pi*(rci + rfo)*htc_net))
        return residue
    sol = fsolve(res, Tci + 100)
    return sol[0]


def erf(x):
    return scipy.special.erf(x)


def Kint(T):
    # Clamp (not abs/fold): folding a negative excursion onto its positive
    # mirror creates a spurious second root at -T that fsolve/least_squares
    # can lock onto, since Kint(-T) == Kint(T) either way. Clamping to a
    # floor keeps the function monotonic so the solver gets pushed back
    # toward the feasible region instead of finding a false match.
    T = np.maximum(T, 1.0)
    tau = T/1000
    a = 16.35
    Term1 = 7.00155*np.log((tau + 0.471675)/(tau + 4.42356))
    Term2 = 6400*(np.exp(-16.35/tau)/(a*np.sqrt(tau)) - np.sqrt(np.pi/a)/(2*a**3)*erf(np.sqrt(a/tau)))
    return 1000*(Term1 + Term2)


def Kfo(T):
    T = np.maximum(T, 1.0)
    tau = T/1000
    a = 16.35
    Term1 = (7.5408 + 17.692*tau + 3.6142*tau**2)**(-1)
    Term2 = 6400*tau**(-5/2) * np.exp(-16.35/tau)
    return Term1 + Term2


def HeatEqn(qvol, A1, A2, r):
    Tfunc = -0.25*qvol*r**2 + A1*np.log(r) + A2
    return Tfunc


def qp(r, qvol, A1):
    qpval = 2*np.pi*r * (qvol/2*r - A1/r)
    return qpval


def T_at_r(q_ppp, A1, A2, r, guess):
    # HeatEqn gives K(T) (the conductivity-integral, not T itself) at r, so
    # recovering the actual temperature means inverting Kint.
    K_target = HeatEqn(q_ppp, A1, A2, r)

    def res(T):
        return Kint(T) - K_target
    return fsolve(res, guess)[0]


def peak_fuel_T(q_ppp, A1, A2, rfo_i, rfo_o, Tfo_i, Tfo_o):
    # The peak is either at whichever fuel surface is hotter, or at the
    # interior point where dT/dr=0 (equivalently dK/dr=0, since dK/dT=k(T)>0
    # always) if that point falls inside the fuel annulus: solving
    # -0.5*qvol*r + A1/r = 0 gives r_star^2 = 2*A1/qvol.
    Tmax = max(Tfo_i, Tfo_o)
    if q_ppp > 0:
        r_star_sq = 2*A1/q_ppp
        if r_star_sq > 0:
            r_star = np.sqrt(r_star_sq)
            if rfo_i < r_star < rfo_o:
                T_star = T_at_r(q_ppp, A1, A2, r_star, Tmax + 200)
                Tmax = max(Tmax, T_star)
    return Tmax


def qp_new(Property, Tm_i, Tm_o, p, qp_i, qp_o, qp_total, C0_Guess, inputs):
    G_i, G_o = inputs['G_i'], inputs['G_o']
    rco_i, rco_o = inputs['rco_i'], inputs['rco_o']
    tc_i, tc_o = inputs['tc_i'], inputs['tc_o']
    kc_i, kc_o = inputs['kc_i'], inputs['kc_o']
    delta = inputs['delta']
    pitch = inputs['pitch']

    Cir_o = 2*np.pi*rco_o
    d_i = 2*rco_i
    d_o = 2*rco_o
    rci_i = rco_i + tc_i
    rci_o = rco_o - tc_o
    rfo_i = rci_i + delta
    rfo_o = rci_o - delta
    A_fuel = np.pi*(rfo_o**2 - rfo_i**2)
    # Fixed by the actual axial power shape, NOT by the trial (qp_i+qp_o):
    # see SCA_Clear_2.py for the full derivation of why q_ppp must come from
    # qp_total rather than being re-derived from the trial split.
    q_ppp = qp_total/A_fuel

    A_o = pitch**2 - np.pi*rco_o**2
    Dh = 4*A_o/Cir_o

    Psi = psi(pitch, d_o)

    htc_conv_i = htc_scw(Property, Tm_i, qp_i, p, G_i, d_i)
    htc_conv_o = htc_scw(Property, Tm_o, qp_o, p, G_o, Dh)*Psi

    Tco_i = Tm_i + qp_i/(2*np.pi*rco_i*htc_conv_i)
    j_i = np.log(rci_i/rco_i) if rci_i > rco_i else np.log(rco_i/rci_i)
    Tci_i = Tco_i + qp_i/(2*np.pi*kc_i)*j_i

    Tco_o = Tm_o + qp_o/(2*np.pi*rco_o*htc_conv_o)
    j_o = np.log(rco_o/rci_o) if rco_o > rci_o else np.log(rci_o/rco_o)
    Tci_o = Tco_o + qp_o/(2*np.pi*kc_o)*j_o

    Tfo_i = gap(qp_i, delta, Tci_i, rci_i, rfo_i)
    Tfo_o = gap(qp_o, delta, Tci_o, rci_o, rfo_o)

    def func(x):
        A1, A2 = x
        fi = HeatEqn(q_ppp, A1, A2, rfo_i)
        fo = HeatEqn(q_ppp, A1, A2, rfo_o)
        kint_i = Kint(Tfo_i)
        kint_o = Kint(Tfo_o)
        return [kint_i - fi, kint_o - fo]
    sol = fsolve(func, C0_Guess)
    A1sol, A2sol = sol[0], sol[1]

    qp_i_new = qp(rfo_i, q_ppp, A1sol)
    qp_o_new = qp(rfo_o, q_ppp, A1sol)

    Tmax = peak_fuel_T(q_ppp, A1sol, A2sol, rfo_i, rfo_o, Tfo_i, Tfo_o)

    return [qp_i_new, qp_o_new], [A1sol, A2sol], Tmax


def LHGR(Property, Tm_i, Tm_o, p, qp_total, Cguess, inputs):
    Tm_i = np.abs(float(Tm_i))
    Tm_o = np.abs(float(Tm_o))
    Cg_state = {'C': list(Cguess)}
    qp_scale = max(abs(qp_total), 1.0)

    def residual(x):
        qp_i, qp_o = x
        qpvec, Avec, _ = qp_new(Property, Tm_i, Tm_o, p, qp_i, qp_o, qp_total, Cg_state['C'], inputs)
        Cg_state['C'] = Avec
        qp_i_new, qp_o_new = -qpvec[0], qpvec[1]
        return [(qp_i - qp_i_new)/qp_scale, (qp_o - qp_o_new)/qp_scale]

    x0 = [qp_total/2, qp_total/2]
    sol = fsolve(residual, x0)
    qp_i_sol, qp_o_sol = sol[0], sol[1]

    qpvec, Avec, Tmax = qp_new(Property, Tm_i, Tm_o, p, qp_i_sol, qp_o_sol, qp_total, Cg_state['C'], inputs)
    return qp_i_sol, qp_o_sol, Avec, Tmax


# =============================================================================
# Axial marching solution: cosine power shape over a channel of length L,
# coupling the SCW (inner) and Pb (outer) coolant enthalpy balances to the
# LHGR solve above at each axial node.
# =============================================================================
def run_SCA(inputs, pval, Tscw_in, TPb_in, q0, L=4.0, n=400, scw_table=None):
    """Runs the same axial march as SCA_Clear_2.py's __main__ block for one
    set of (geometry+flow) inputs and operating conditions, and returns the
    axial profiles as plain arrays instead of only plotting them.

    inputs   : dict with the same keys as SCA_Clear_2.py's `input` dict
               (pitch, rco_i, rco_o, tc_i, tc_o, delta, kc_i, kc_o, G_i, G_o)
    pval     : SCW pressure [MPa] (held constant along the channel)
    Tscw_in  : SCW inlet temperature [K]
    TPb_in   : Pb inlet temperature [K]
    q0       : peak linear heat generation rate [W/m] (cosine axial shape)
    L        : active fuel length [m]
    n        : number of axial nodes
    scw_table: optional pre-built build_scw_table(pval) dict, to skip
               rebuilding the SCW property table when many runs share the
               same pval (as the PINN data generator does)
    """
    if scw_table is None:
        scw_table = build_scw_table(pval)
    Property = make_Property(scw_table)

    dz = L/n
    Z = np.arange(-L/2 + dz, L/2 + dz, dz)

    def q_p(z):
        return q0*np.cos(np.pi*z/L)

    A_flow_i = np.pi*inputs['rco_i']**2
    A_flow_o = inputs['pitch']**2 - np.pi*inputs['rco_o']**2
    mdot_i = inputs['G_i']*A_flow_i
    mdot_o = inputs['G_o']*A_flow_o

    hin_scw = Property(['T', Tscw_in], 'h')
    hin_Pb = Property(['T', Tscw_in], 'h')

    qp0 = q_p(-L/2 + dz/2)
    qp0_i, qp0_o, C0_guess, Tmax0 = LHGR(Property, Tscw_in, TPb_in, pval, qp0, [1000, 1000], inputs)

    h0_scw = hin_scw + qp0_i*dz/mdot_i
    h0_pb = hin_Pb + qp0_o*dz/mdot_o
    T0_i = float(Property(['h', h0_scw], 'T'))
    T0_o = float(Property(['h', h0_pb], 'T'))

    qpI, qpO = [qp0_i], [qp0_o]
    h_i, h_o = [h0_scw], [h0_pb]
    T_i, T_o = [T0_i], [T0_o]
    T_fuel_max = [Tmax0]

    for i in range(1, n):
        z = Z[i]
        qp_local = q_p(z - dz/2)
        Ti, To = T_i[i-1], T_o[i-1]
        qp_i, qp_o, C0_guess, Tmax = LHGR(Property, Ti, To, pval, qp_local, C0_guess, inputs)

        h_scw = h_i[i-1] + qp_i*dz/mdot_i
        T_scw = float(Property(['h', h_scw], 'T'))

        h_pb = h_o[i-1] + qp_o*dz/mdot_o
        T_pb = float(Property(['h', h_pb], 'T'))#T_Pb(h_pb)

        qpI.append(qp_i); qpO.append(qp_o)
        h_i.append(h_scw); h_o.append(h_pb)
        T_i.append(T_scw); T_o.append(T_pb)
        T_fuel_max.append(Tmax)

    return {
        'Z': Z, 'T_i': np.array(T_i), 'T_o': np.array(T_o),
        'qpI': np.array(qpI), 'qpO': np.array(qpO),
        'T_fuel_max': np.array(T_fuel_max),
    }


if __name__ == '__main__':
    import time
    import matplotlib.pyplot as plt

    inputs = {
        "pitch":  0.06, "rco_i": 0.01, "rco_o": 0.025,
        "tc_i":   0.00055, "tc_o": 0.00055, "delta": 5e-4,
        "kc_i":   24, "kc_o": 24, "G_i": 800, "G_o": 600,
    }

    t0 = time.time()
    out = run_SCA(inputs, pval=25, Tscw_in=300+273.15, TPb_in=600, q0=35e3, L=3, n=400)
    print(f"run_SCA (400 axial steps) elapsed: {time.time()-t0:.2f} s "
          f"(baseline SCA_Clear_2.py took ~6 min for the same run)")

    peak_idx = int(np.argmax(out['T_fuel_max']))
    print(f"Peak fuel temperature: {out['T_fuel_max'][peak_idx]:.1f} K at "
          f"z = {out['Z'][peak_idx]:.3f} m")

    fig, axes = plt.subplots(1, 3, figsize=(15, 4.5))
    rho_i = IAPWS95.rho_Tp(out['T_i'],25)
    rho_0 = IAPWS95.rho_Tp(out['T_o'],25)
    #plt.plot(out)
    axes[0].plot(out['Z'], out['T_i'], label='SCW Temperature')
    axes[0].plot(out['Z'], out['T_o'], label='Lead Temperature')
    axes[0].set_xlabel('z [m]'); axes[0].set_ylabel('T [K]'); axes[0].legend()

    axes[1].plot(out['Z'], out['qpI'], label='SCW LHGR')
    axes[1].plot(out['Z'], out['qpO'], label='Lead LHGR')
    axes[1].set_xlabel('z [m]'); axes[1].set_ylabel("q' [W/m]"); axes[1].legend()

    axes[2].plot(out['Z'], out['T_fuel_max'], label='Peak fuel temperature')
    axes[2].set_xlabel('z [m]'); axes[2].set_ylabel('T [K]'); axes[2].legend()

    plt.tight_layout()
    plt.savefig('sca_iapws95_check.png', dpi=150)
    plt.show()
    print("Saved plot to sca_iapws95_check.png")